name: Symcon Module Status

on:
  schedule:
    - cron: '0 6 * * *' # Täglich um 6 Uhr morgens
  workflow_dispatch:    # Manuell auslösbar

jobs:
  update-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get list of repos from GitHub API
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/users/Wilkware/repos?per_page=100" > repos.json
          cat repos.json | jq '.[] | select((.description // "") | test("Symcon Modul")) | {name: .name, clone_url: .clone_url}' > filtered_repos.json

      - name: Create module status markdown
        run: |
          echo "| Modul | Version | Typ | Style |" > MODULE_STATUS.md
          echo "|-------|---------|-----|------ |" >> MODULE_STATUS.md

          cat filtered_repos.json | jq -c '.' | while read repo; do
            name=$(echo $repo | jq -r '.name')
            url=$(echo $repo | jq -r '.clone_url')

            echo "Cloning $name"
            git clone --depth=1 $url temp_repo

            echo "Tags found in $name:"
            git -C temp_repo tag --sort=-creatordate

            if [ -f temp_repo/library.json ]; then
              version=$(jq -r '.version' temp_repo/library.json)
              build=$(jq -r '.build' temp_repo/library.json)
              tag=$(git -C temp_repo tag --sort=-creatordate | head -n 1)
              if [[ $tag == *stable ]]; then
                typ="STABLE"
              elif [[ $tag == *beta ]]; then
                typ="BETA"
              elif [[ $tag == *testing ]]; then
                typ="TESTING"
              else
                typ="INTERNAL"
              fi
              case "$typ" in
                STABLE)   color="green" ;;
                BETA)     color="yellow" ;;
                TESTING)  color="red" ;;
                *)        color="lightgrey" ;;
              esac
              echo "| [$name]($url) | $version.$build | ![$typ](https://img.shields.io/badge/$typ-$color?style=flat-square&format=png) | [![Action](https://img.shields.io/github/actions/workflow/status/Wilkware/$name/style.yml?branch=main&label=Test&style=flat-square)](https://github.com/Wilkware/$name/actions) |" >> MODULE_STATUS.md
            else
              echo "| [$name]($url) | - | - | - |" >> MODULE_STATUS.md
            fi
            rm -rf temp_repo
          done

      - name: Update README.md with module status
        run: |
            content=$(cat MODULE_STATUS.md)
            awk -v repl="$content" '
            BEGIN { inside=0 }
            /<!-- SYMCON MODULE START -->/ {
                print; print repl; inside=1; next
            }
            /<!-- SYMCON MODULE END -->/ {
            inside=0
            }
            !inside
            ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update module status in README [skip ci]" || echo "No changes to commit"
          git push
