name: Test Action

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test-Ausgabe
        run: |
          echo Hallo
          echo "World"
        shell: bash